//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Party = new HashSet<Party>();
            this.Party1 = new HashSet<Party>();
            this.Party2 = new HashSet<Party>();
        }
    
        public long id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<Party> Party { get; set; }
        public virtual ICollection<Party> Party1 { get; set; }
        public virtual ICollection<Party> Party2 { get; set; }
    }
}
