//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public Party()
        {
            this.Step = new HashSet<Step>();
        }
    
        public long id { get; set; }
        public long client_owner { get; set; }
        public Nullable<long> client_partner { get; set; }
        public string owner_color { get; set; }
        public Nullable<long> victory_client { get; set; }
        public bool is_finished { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Client Client1 { get; set; }
        public virtual Client Client2 { get; set; }
        public virtual ICollection<Step> Step { get; set; }
    }
}
